apiVersion: v1
kind: Pod
metadata:
  name: "mypod3"
  labels:
    region: IN
    dc: south
    app: web

spec:
  containers:
  - name: "myc1"
    image: "gautamsagar99/sample"
    env:
    - name: x
      value: "5"
